### ISSUE TITLE
Closed-Source?

### ISSUE THREAD

**Issue by taserbolt** [SFC-hacker/MK7-Plugin-Deluxe-3.0.2#1]
I need the source code to be publicly available in order for me to request this to be added to Universal-DB. Just a reminder, not rushing you.

**Comment by SFC-hacker** [comment]
Yes, I'll see what I can do about it. I'm currently stucked on some bug and I still don't know if I should update the plugin :/ . If I do so, I'll publish the source too.
Thank you for your message !
